/**
 * This file contains action constants
 */

export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const NEXT_MODAL = 'NEXT_MODAL';
export const HANDLE_CHANGE_MODAL = 'HANDLE_CHANGE_MODAL';
export const PREVIOUS_MODAL = 'PREVIOUS_MODAL';
export const SUBMIT_MODAL = 'SUBMIT_MODAL';

export const CLEAR_USER_LOGIN = 'CLEAR_USER_LOGIN';
export const POST_USER_LOGIN = 'POST_USER_LOGIN';
export const RECEIVE_POST_USER_LOGIN = 'RECEIVE_POST_USER_LOGIN';
export const RECEIVE_POST_USER_LOGIN_FAILURE = 'RECEIVE_POST_USER_LOGIN_FAILURE';

export const CLEAR_USER_LOGOUT = 'CLEAR_USER_LOGOUT';
export const POST_USER_LOGOUT = 'POST_USER_LOGOUT';
export const RECEIVE_POST_USER_LOGOUT = 'RECEIVE_POST_USER_LOGOUT';
export const RECEIVE_POST_USER_LOGOUT_FAILURE = 'RECEIVE_POST_USER_LOGOUT_FAILURE';

export const CLEAR_ADMIN_LOGIN = 'CLEAR_ADMIN_LOGIN';
export const POST_ADMIN_LOGIN = 'POST_ADMIN_LOGIN';
export const RECEIVE_POST_ADMIN_LOGIN = 'RECEIVE_POST_ADMIN_LOGIN';
export const RECEIVE_POST_ADMIN_LOGIN_FAILURE = 'RECEIVE_POST_ADMIN_LOGIN_FAILURE';

export const CLEAR_ADMIN_LOGOUT = 'CLEAR_ADMIN_LOGOUT';
export const POST_ADMIN_LOGOUT = 'POST_ADMIN_LOGOUT';
export const RECEIVE_POST_ADMIN_LOGOUT = 'RECEIVE_POST_ADMIN_LOGOUT';
export const RECEIVE_POST_ADMIN_LOGOUT_FAILURE = 'RECEIVE_POST_ADMIN_LOGOUT_FAILURE';

export const CLEAR_SEARCH = 'CLEAR_SEARCH';
export const GET_SEARCH = 'GET_SEARCH';
export const RECEIVE_GET_SEARCH = 'RECEIVE_GET_SEARCH';
export const RECEIVE_GET_SEARCH_FAILURE = 'RECEIVE_GET_SEARCH_FAILURE';
export const KEEP_SEARCH_ON_REDIRECT = 'KEEP_SEARCH_RESULT_ON_REDIRECT';

export const CLEAR_SELECTED_SELECTION_ADVISER = 'CLEAR_SELECTED_SELECTION_ADVISER';
export const INIT_SELECTED_SELECTION_ADVISER = 'INIT_SELECTED_SELECTION_ADVISER';
export const SET_SELECTED_SELECTION_ADVISER = 'SET_SELECTED_SELECTION_ADVISER';
export const ADD_SELECTED_SELECTION_ADVISER = 'ADD_SELECTED_SELECTION_ADVISER';
export const CHANGE_INFO_SELECTED_SELECTION_ADVISER = 'CHANGE_INFO_SELECTED_SELECTION_ADVISER';
export const REMOVE_SELECTED_SELECTION_ADVISER = 'REMOVE_SELECTED_SELECTION_ADVISER';

export const SHOW_TOAST = 'SHOW_TOAST';
export const RESET_TOAST = 'RESET_TOAST';